const getRandomElement = require("../utils/getRandomElement");

module.exports = {
	name: "note",
	description: "send a random note",
	execute(message, args) {
		const notes = [
			"my fav place is inside your hug… but your arms better be ready 😌💚",
			"stop being so attractive, it’s very distracting 😤💙",
			"why do you look good even when you do nothing?? unfair 😒💜",
			"I’d choose you in every universe… but you better choose me first 😏❤️",
			"come here, I need to inspect how handsome you are 🧐💛",
			"your smile should come with a warning label 😩💖",
			"I miss you… so when are you coming to fix that? 😌💚",
			"if I stare at you too long don’t blame me 👀💙",
			"you’re lucky I’m obsessed with you 🙄💜",
			"I fall for you every day… and you don’t even catch me 😤❤️",
			"why are you so hardworking and so fine?? pick a struggle 😮‍💨💛",
			"I like you… but I also like teasing you more 😏💖",
			"your arms are my home address — no shifting allowed 🏡💚",
			"I feel safest when I’m annoying you 🤭💙",
			"don’t act innocent, you know exactly what you’re doing to me 😌💜",
			"I’d hug you tight… maybe a little longer than necessary 😏❤️",
			"you make my heart race and it’s your fault 🫣💛",
			"stop being cute or I’ll have to kiss you 😤💖",
			"I love how soft you are… even if you pretend not to be 😌💚",
			"your voice is dangerously attractive 🎧💙",
			"why do I blush because of YOU?? control yourself 😒💜",
			"I like being yours… feels exclusive 😏❤️",
			"you’re my comfort person and my favorite distraction 😌💛",
			"I wanna hold your face and just stare at you 🫠💖",
			"if loving you is a crime, I’m not even sorry 🫢💚",
			"you better miss me as much as I miss you 😤💙",
			"I love when you try to act serious… it’s cute 🤭💜",
			"you’re stuck with me forever, no refunds 😌❤️",
			"I’d pause the world just to sit close to you 🕰️💛",
			"your hugs fix everything… so when’s my next appointment? 😏💖",
			"I feel butterflies every time you look at me 🦋💚",
			"don’t smile at me like that… I’m weak 😮‍💨💙",
			"you’re my safe space… but also my weakness 😌💜",
			"I admire you… but I also wanna steal you away 😏❤️",
			"your texts make my whole mood change instantly 📲💛",
			"I love how patient you are with my drama 😌💖",
			"you make me feel things I can’t even explain 🫣💚",
			"if you keep being this cute, I’m not responsible for my actions 😏💙",
			"I like when you look at me like that… don’t stop 😌💜",
			"you make ordinary moments feel special ✨❤️",
			"I’d choose your arms over anything 💞💛",
			"why are you so clingy? oh wait that’s me 🤭💖",
			"I love how you care for me in little ways 🌸💚",
			"you + me = dangerous level of chemistry 😏💙",
			"I’m proud of you… and slightly obsessed too 😌💜",
			"your presence alone makes me soft 🧸❤️",
			"I wanna sit close to you and pretend I’m not blushing 😳💛",
			"you’re my favorite habit and my favorite person 💖",
			"I feel complete when I’m with you 🫶💚",
			"come here… I owe you a long hug 😌💙",
		];
		const randomNote = getRandomElement(notes);
		message.channel.send(randomNote);
	},
};
